### ISSUE TITLE
Detección en las caras

### ISSUE THREAD

**Issue by Sebastian-Fals** [JohanRengifo/FacialSystem-Front#2]
Para que se pueda generar la detección de caras se debe poder guardar una foto de referencia en el usuario, y en base a eso hacer la autentificación

**Comment by JohanRengifo** [comment]
Claro, las funciones de parte del servidor estan configuradas para eso,m al momento de detectar un rostro, el umbral de distancia, asegura la distancia perfecta y toma un snapshot, este es procesado (Extracción de los descriptores) y posteriormente enviado o comparado con la DB.
